version: '3.7'

# Define services
services:
  # App backend service
  app-server:
    # Configuration for building the docker image for the backend service
    build:
      context: backend # Use an image built from the specified dockerfile in the `polling-app-server` directory.
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Forward the exposed port 8080 on the container to port 8080 on the host machine
    restart: always
    depends_on:
      - db # This service depends on mysql. Start that first.
      - keycloak-auth # This service depends on mysql. Start that first.
    environment: # Pass environment variables to the service
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/polls?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: callicoder
      SPRING_DATASOURCE_PASSWORD: callicoder
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - backend
      - frontend

  # Database Service (Mysql)
  db:
    image: mysql:8
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: polls
      MYSQL_USER: callicoder
      MYSQL_PASSWORD: callicoder
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend

  # App backend service
  keycloak-auth:
    # Configuration for building the docker image for the backend service
    build:
      context: keycloak # Use an image built from the specified dockerfile in the `polling-app-server` directory.
      dockerfile: Dockerfile
    ports:
      - "8000:8080" # Forward the exposed port 8080 on the container to port 8000 on the host machine
    restart: always
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - backend
      - frontend

  # App frontend service
  app-client-next:
    # Configuration for building the docker image for the backend service
    build:
      context: frontend # Use an image built from the specified dockerfile in the `polling-app-server` directory.
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Forward the exposed port 8080 on the container to port 8000 on the host machine
    restart: always
    depends_on:
      - app-server # This service depends on mysql. Start that first.
      - keycloak-auth # This service depends on mysql. Start that first.
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - frontend

# Volumes
volumes:
  db-data:

# Networks to be created to facilitate communication between containers
networks:
  backend:
  frontend:    
